title:              How's it going?
email:              schuylerbishop3@gmail.com
description:        A very brief description.
author:             author
#baseurl:            ""
url:                "https://skyebishop.github.io"

# Social Profiles
github_username:    skyebishop
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
